[phases.setup]
nixPkgs = ['nodejs_20', 'python3']

[phases.install]
dependsOn = ['setup']
cmds = ['cd rick-morty-ecommerce && npm ci']

[phases.build]
dependsOn = ['install']
cmds = ['cd rick-morty-ecommerce && npm run build']

[start]
cmd = 'cd rick-morty-ecommerce && npm start'

[variables]
NODE_ENV = 'production' 